


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5061:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: almacen-luz
    volumes:
      - ./postgres:/var/lib/postgresql/data
